# Generated by Django 4.1.5 on 2023-02-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBomberos', '0002_seccion_rename_seccion_bombero_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_division', models.CharField(max_length=30)),
                ('encargados_division', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=40)),
                ('encargado_guardia', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='seccion',
        ),
        migrations.AddField(
            model_name='bombero',
            name='division',
            field=models.CharField(default=-3, max_length=40),
            preserve_default=False,
        ),
    ]
